const vocabulario = {
  can: { pronuncia: "kén", significado: "Poder" },
  tell: { pronuncia: "tél", significado: "Contar" },
  go: { pronuncia: "gô", significado: "Ir" },
  offer: { pronuncia: "ófer", significado: "Oferecer" },
  build: { pronuncia: "bild", significado: "Construir" },
  give: { pronuncia: "guive", significado: "Dar" },
  say: { pronuncia: "sei", significado: "Dizer" },
  know: { pronuncia: "nôo", significado: "Saber" },
  want: { pronuncia: "uant", significado: "Querer" },
  watch: { pronuncia: "uátch", significado: "Assistir" },
  hit: { pronuncia: "ríter", significado: "Bater" },

  live: [
    { pronuncia: "laive", significado: "Viver" },
    { pronuncia: "laive", significado: "Morar" }
  ],

  hug: { pronuncia: "râg", significado: "Abraçar" },
  hate: { pronuncia: "râiter", significado: "Odiar" },
  feel: { pronuncia: "fíel", significado: "Sentir" },
  read: { pronuncia: "whíd", significado: "Ler" },
  erase: { pronuncia: "arhês", significado: "Apagar" },
  see: { pronuncia: "si", significado: "Ver" },
  do: { pronuncia: "du", significado: "Fazer" },
  write: { pronuncia: "rúate", significado: "Escrever" },
  understand: { pronuncia: "andesten", significado: "Entender" },
  hear: { pronuncia: "ríer", significado: "Ouvir" },
  ask: { pronuncia: "asque", significado: "Pedir" },
  arrive: { pronuncia: "arhaíve", significado: "Chegar" },
  leave: { pronuncia: "líve", significado: "Sair" },
  buy: { pronuncia: "bai", significado: "Comprar" },
  sell: { pronuncia: "séu", significado: "Vender" },
  have: { pronuncia: "héve", significado: "Ter" },
  help: { pronuncia: "hélp", significado: "Ajudar" },
  think: { pronuncia: "fhínk", significado: "Pensar" },
  sleep: { pronuncia: "slíp", significado: "Dormir" },
  wake: { pronuncia: "uêque", significado: "Acordar" },
  break: { pronuncia: "brâque", significado: "Quebrar" },
  wait: { pronuncia: "uêt", significado: "Esperar" },
  start: { pronuncia: "estarte", significado: "Começar" },
  finish: { pronuncia: "fíniche", significado: "Terminar" },
  run: { pronuncia: "rhân", significado: "Correr" },
  walk: { pronuncia: "uálque", significado: "Andar" },
  believe: { pronuncia: "belíve", significado: "Acreditar" },
  invite: { pronuncia: "invai", significado: "Convidar" },
  travel: { pronuncia: "thrável", significado: "Viajar" },
  take: { pronuncia: "tchêque", significado: "Levar" },
  bring: { pronuncia: "bhrím", significado: "Trazer" },
  sit: { pronuncia: "sít", significado: "Sentar" },
  show: { pronuncia: "shôu", significado: "Mostrar" },
  teach: { pronuncia: "thít", significado: "Ensinar" },
  learn: { pronuncia: "lan", significado: "Aprender" },
  change: { pronuncia: "chênge", significado: "Mudar" },
  care: { pronuncia: "quero", significado: "Cuidar" },
  cut: { pronuncia: "kãt", significado: "Cortar" },
  forget: { pronuncia: "fôrgé", significado: "Esquecer" },
  remember: { pronuncia: "rhémembêr", significado: "Lembrar" },
  cry: { pronuncia: "chrái", significado: "Chorar" },
  laugh: { pronuncia: "láf", significado: "Rir" },
  explain: { pronuncia: "écsplén", significado: "Explicar" },

  call: [
    { pronuncia: "kál", significado: "Ligar" },
    { pronuncia: "kál", significado: "Chamar" }
  ],

  die: { pronuncia: "dái", significado: "Morrer" },
  make: { pronuncia: "mêke", significado: "Fazer" },
  develop: { pronuncia: "dêvélop", significado: "Desenvolver" },
  agree: { pronuncia: "agrí", significado: "Concordar" },
  grow: { pronuncia: "grôu", significado: "Crescer" },
  decrease: { pronuncia: "dêcrhis", significado: "Diminuir" },

  get: [
    { pronuncia: "gét", significado: "Conseguir" },
    { pronuncia: "gét", significado: "Receber" }
  ],

  smile: { pronuncia: "smai-ol", significado: "Sorrir" },
  stay: { pronuncia: "estêy", significado: "Ficar" },
  spend: { pronuncia: "espende", significado: "Passar" },
  divide: { pronuncia: "diváid", significado: "Dividir" },
  open: { pronuncia: "ôpen", significado: "Abrir" },
  close: { pronuncia: "clôs", significado: "Fechar" },
  jump: { pronuncia: "dhíampe", significado: "Pular" },
  fall: { pronuncia: "fál", significado: "Cair" },
  cook: { pronuncia: "câque", significado: "Cozinhar" },
  wash: { pronuncia: "uáche", significado: "Lavar" },
  dry: { pronuncia: "drhái", significado: "Secar" },
  search: { pronuncia: "sôrche", significado: "Procurar" },
  find: { pronuncia: "fáind", significado: "Encontrar" },
  protect: { pronuncia: "protéct", significado: "Proteger" },
  receive: { pronuncia: "rhêcíve", significado: "Receber" },
  send: { pronuncia: "cénde", significado: "Enviar" },
  obey: { pronuncia: "ôhbê", significado: "Obedecer" },
  swim: { pronuncia: "súén", significado: "Nadar" },
  bathe: { pronuncia: "beidhe", significado: "Banhar" },
  dream: { pronuncia: "drhúime", significado: "Sonhar" },
  shine: { pronuncia: "sháine", significado: "Brilhar" },
  come: { pronuncia: "cãm", significado: "Vir" },
  appear: { pronuncia: "apíer", significado: "Aparecer" },
  try: { pronuncia: "thrái", significado: "Tentar" },
  look: { pronuncia: "lôk", significado: "Olhar" },
  listen: { pronuncia: "lísn", significado: "Escutar" },
  connect: { pronuncia: "conect", significado: "Ligar" },
  "turn off": { pronuncia: "thrârn off", significado: "Desligar" },
  brush: { pronuncia: "brâsh", significado: "Escovar" },
  sing: { pronuncia: "síngue", significado: "Cantar" },
  dance: { pronuncia: "dênce", significado: "Dançar" },
  back: { pronuncia: "béck", significado: "Voltar" },
  pay: { pronuncia: "pêi", significado: "Pagar" },
  lose: { pronuncia: "lú-ous", significado: "Perder" },
  win: { pronuncia: "uín", significado: "Ganhar" },
  study: { pronuncia: "estâre", significado: "Estudar" },
  choose: { pronuncia: "tchúuz", significado: "Escolher" }
};

window.vocabulario = vocabulario;
